version: '3.8'

services:

    project-paja-usher-rule:

        container_name: project-paja-usher-rule
        
        image: softwareshinobi/project-paja-usher-rule

        build: 

            context: .

            dockerfile: Dockerfile

        restart: unless-stopped

        ports:

            - "8888:8888"
