version: '3.8'

services:

    project-chimba:

        container_name: project-chimba
        
        image: softwareshinobi/project-chimba

        build: 

            context: .

            dockerfile: Dockerfile

        restart: unless-stopped

        ports:

            - "8888:8888"
