version: "3"

services:

    usher-rule-trading-robot-docs:

        container_name: usher-rule-trading-robot-docs

        image: titom73/mkdocs
      
        restart: "unless-stopped"

        volumes:
        
            - ./docs:/docs/    
            
            - ${PWD}/mkdocs.yml:/docs/mkdocs.yml
            
        ports:

            - 8888:8000
