services:

    docs:

        container_name: docs

        image: titom73/mkdocs

        volumes:
        
            - ${PWD}:/docs/
            
            - ${PWD}/mkdocs.yml:/docs/mkdocs.yml
         
        ports:

            - 8882:8000
